#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Instruct the color library to enable color output regardless of the environment.
export FORCE_COLOR=1

# Store the original commit message
COMMIT_MSG_FILE="$GIT_DIR/COMMIT_EDITMSG"
if [ -f "$COMMIT_MSG_FILE" ]; then
  COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
else
  COMMIT_MSG=""
fi

# Format JavaScript code
npm run format

# Stage any changes made by formatting
if ! git diff --quiet; then
  git add -u

  # Reapply the original commit message to the new staged changes
  if [ -n "$COMMIT_MSG" ]; then
    echo "$COMMIT_MSG" > "$COMMIT_MSG_FILE"
  fi
fi